### PR TITLE
Added Scarlet Witch cards

### PR DESCRIPTION
**Pull request by q3c0**
Hello, 

I tried to update marveldb-json-data in order to add Scarlet Witch to OCTGN as it was missing. I will be also try to work on Kang. As my experience with open-source projects is limited and that I tried to understand what a couple of scripts in this project did, I will be glad to receive feedback on this.

I am also trying to figure out how to add the custom game to OCTGN to test it.

### CODE REVIEW

**Comment by twistedsistem** [comment]
Only issue that I see with this right now is that the nemesis deck is under the "Special Decks" section and not the Nemesis deck sections and also doesn't have the right name scheme for it to work correctly.

**Comment by q3c0** [comment]
Hi Twisted!

I just tried with the out of the box and with a new one created with the deck editor but in both cases the nemesis were not under the special decks and was correctly placed in the nemesis one:
image

Where are you seeing them in the Special? 

I noticed that I put Slipping Sanity under owner scw and not scw_nemesis, is this what you are referring when you said that they don't have the right name scheme to work correctly? I will change it ASAP.
image

Another thing that I just noticed right now is that when the Villain Deck is loaded, only one of Slipping Sanity is automatically inserted in the encounter deck, the other stays in the nemesis deck. I will check if I can fix this.

**Comment by q3c0** [comment]
I should have fixed both issues, unfortunately I don't know if I managed correctly git at this point...

**Comment by twistedsistem** [comment]
Sometimes I hate git.....when I was reviewing your SCW changes it showed that the scw nemsis cards were under the "special decks", but really they were in the right spot.

Thanks I am going to merge this stuff today and work through some testing.

**Comment by q3c0** [comment]
No worries, the owner for the obligation was wrong anyway and wouldn't have catched that, moreover I didn't make it easy with the commits :)

**Pull request merged**
